"""Course short code, parsed title, and user nickname

Revision ID: 458e37f3ce83
Revises: 0001
Create Date: 2026-09-09 12:01:14.940618
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "458e37f3ce83"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("courses", sa.Column("short_code", sa.String(length=32), nullable=True))
    op.add_column("courses", sa.Column("title", sa.Text(), nullable=True))
    op.add_column("courses", sa.Column("nickname", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("courses", "nickname")
    op.drop_column("courses", "title")
    op.drop_column("courses", "short_code")
    # ### end Alembic commands ###
