"""Contacts, manual items, settings

Revision ID: b94ea274cdcd
Revises: 458e37f3ce83
Create Date: 2026-09-09 17:00:47.724423
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b94ea274cdcd"
down_revision: str | None = "458e37f3ce83"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _existing_tables() -> set[str]:
    bind = op.get_bind()
    try:
        from sqlalchemy import inspect as sa_inspect

        return set(sa_inspect(bind).get_table_names())
    except Exception:
        return set()


def _existing_indexes(table: str) -> set[str]:
    bind = op.get_bind()
    try:
        from sqlalchemy import inspect as sa_inspect

        return {i["name"] for i in sa_inspect(bind).get_indexes(table)}
    except Exception:
        return set()


def upgrade() -> None:
    # 0001 uses Base.metadata.create_all, so fresh DBs already have these tables.
    existing = _existing_tables()
    if "settings" in existing and "contacts" in existing and "manual_items" in existing:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    if "settings" not in existing:
        op.create_table(
            "settings",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key"),
    )
    if "contacts" not in existing:
        op.create_table(
            "contacts",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("course_id", sa.Integer(), nullable=True),
            sa.Column("name", sa.String(length=256), nullable=True),
            sa.Column("email", sa.String(length=320), nullable=False),
            sa.Column("role", sa.String(length=64), nullable=True),
            sa.Column("source", sa.String(length=32), nullable=False),
            sa.Column("source_quote", sa.Text(), nullable=True),
            sa.Column("confirmed_by_user", sa.Boolean(), nullable=False),
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            ),
            sa.ForeignKeyConstraint(
                ["course_id"],
                ["courses.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("course_id", "email", name="uq_contact_per_course"),
        )
    c_idx = _existing_indexes("contacts") if "contacts" in _existing_tables() else set()
    if "ix_contacts_course_id" not in c_idx:
        op.create_index(op.f("ix_contacts_course_id"), "contacts", ["course_id"], unique=False)
    if "ix_contacts_email" not in c_idx:
        op.create_index(op.f("ix_contacts_email"), "contacts", ["email"], unique=False)
    if "manual_items" not in existing:
        op.create_table(
            "manual_items",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("course_id", sa.Integer(), nullable=True),
            sa.Column("title", sa.Text(), nullable=False),
            sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("kind", sa.String(length=32), nullable=False),
            sa.Column("notes", sa.Text(), nullable=True),
            sa.Column("done", sa.Boolean(), nullable=False),
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            ),
            sa.ForeignKeyConstraint(
                ["course_id"],
                ["courses.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
        )
    m_idx = _existing_indexes("manual_items") if "manual_items" in _existing_tables() else set()
    if "ix_manual_items_course_id" not in m_idx:
        op.create_index(
            op.f("ix_manual_items_course_id"), "manual_items", ["course_id"], unique=False
        )
    if "ix_manual_items_due_at" not in m_idx:
        op.create_index(op.f("ix_manual_items_due_at"), "manual_items", ["due_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    tables = _existing_tables()
    if "manual_items" in tables:
        idx = _existing_indexes("manual_items")
        if "ix_manual_items_due_at" in idx:
            op.drop_index(op.f("ix_manual_items_due_at"), table_name="manual_items")
        if "ix_manual_items_course_id" in idx:
            op.drop_index(op.f("ix_manual_items_course_id"), table_name="manual_items")
        op.drop_table("manual_items")
    if "contacts" in tables:
        idx = _existing_indexes("contacts")
        if "ix_contacts_email" in idx:
            op.drop_index(op.f("ix_contacts_email"), table_name="contacts")
        if "ix_contacts_course_id" in idx:
            op.drop_index(op.f("ix_contacts_course_id"), table_name="contacts")
        op.drop_table("contacts")
    if "settings" in tables:
        op.drop_table("settings")
