"""Guided setup wizard helpers (testable, HTTP-mockable)."""

from __future__ import annotations

import secrets
from zoneinfo import ZoneInfo, available_timezones

import httpx

from canvasbuddy.slots import parse_slot


def validate_timezone(tz: str) -> bool:
    try:
        ZoneInfo(tz.strip())
        return True
    except Exception:
        return False


def suggest_timezones(prefix: str = "America/") -> list[str]:
    try:
        return sorted(t for t in available_timezones() if t.startswith(prefix))[:20]
    except Exception:
        return ["America/Edmonton", "America/Toronto", "America/Vancouver"]


def validate_slot_input(role: str, spec: str) -> str:
    """Empty string disables; otherwise must parse. Returns stripped spec."""
    spec = (spec or "").strip()
    if not spec:
        return ""
    parse_slot(role, spec)  # raises ValueError with friendly message
    return spec


def generate_secret() -> str:
    return secrets.token_hex(24)


async def check_canvas(base_url: str, token: str, client: httpx.AsyncClient | None = None) -> dict:
    """GET /users/self + courses. Returns {user, courses, terms}."""
    base = base_url.strip().rstrip("/")
    if not base.endswith("/api/v1"):
        base = base + "/api/v1"
    own = client or httpx.AsyncClient(timeout=15.0)
    close = client is None
    try:
        r = await own.get(f"{base}/users/self", headers={"Authorization": f"Bearer {token}"})
        if r.status_code == 401:
            raise RuntimeError("Canvas rejected the token (401). Make a new one.")
        r.raise_for_status()
        user = r.json()
        c = await own.get(
            f"{base}/courses",
            params={"enrollment_state": "active", "per_page": 100},
            headers={"Authorization": f"Bearer {token}"},
        )
        c.raise_for_status()
        courses = c.json()
        terms = sorted({(x.get("term") or {}).get("name") or "?" for x in courses})
        return {"user": user, "courses": courses, "terms": terms}
    finally:
        if close:
            await own.aclose()


async def check_telegram_bot(token: str, client: httpx.AsyncClient | None = None) -> dict:
    own = client or httpx.AsyncClient(timeout=15.0)
    close = client is None
    try:
        r = await own.get(f"https://api.telegram.org/bot{token}/getMe")
        r.raise_for_status()
        data = r.json()
        if not data.get("ok"):
            raise RuntimeError(f"Telegram getMe failed: {data}")
        return data["result"]
    finally:
        if close:
            await own.aclose()


async def detect_chat_id(token: str, client: httpx.AsyncClient | None = None) -> str | None:
    """Read getUpdates and return the most recent private chat id, if any."""
    own = client or httpx.AsyncClient(timeout=15.0)
    close = client is None
    try:
        r = await own.get(f"https://api.telegram.org/bot{token}/getUpdates", params={"timeout": 0})
        r.raise_for_status()
        updates = r.json().get("result", [])
        for u in reversed(updates):
            chat = ((u.get("message") or {}).get("chat")) or (
                (u.get("edited_message") or {}).get("chat")
            )
            if chat and chat.get("id"):
                return str(chat["id"])
        return None
    finally:
        if close:
            await own.aclose()


async def check_slack_webhook(url: str, client: httpx.AsyncClient | None = None) -> None:
    own = client or httpx.AsyncClient(timeout=10.0)
    close = client is None
    try:
        r = await own.post(url, json={"text": "StudyBuddy test — your Slack webhook works. ✅"})
        if r.status_code != 200:
            raise RuntimeError(f"Slack returned {r.status_code}: {r.text[:200]}")
    finally:
        if close:
            await own.aclose()


async def check_database(url: str) -> None:
    from sqlalchemy.ext.asyncio import create_async_engine

    eng_url = url
    if eng_url.startswith("postgres://"):
        eng_url = "postgresql://" + eng_url[len("postgres://") :]
    if eng_url.startswith("postgresql://"):
        eng_url = "postgresql+asyncpg://" + eng_url[len("postgresql://") :]
    engine = create_async_engine(eng_url, pool_pre_ping=True)
    try:
        async with engine.connect() as conn:
            await conn.execute(__import__("sqlalchemy").text("SELECT 1"))
    finally:
        await engine.dispose()


def build_env_text(values: dict[str, str]) -> str:
    lines = ["# StudyBuddy — generated by `canvasbuddy setup`. Never commit this file."]
    for k, v in values.items():
        lines.append(f"{k}={v}")
    return "\n".join(lines) + "\n"


def write_env_file(path: str, text: str) -> None:
    import os

    flags = os.O_WRONLY | os.O_CREAT | os.O_TRUNC
    mode = 0o600
    fd = os.open(path, flags, mode)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(text)
    except Exception:
        try:
            os.close(fd)
        except Exception:
            pass
        raise
    try:
        os.chmod(path, mode)
    except Exception:
        pass
